services:
  cyberneuron:
    image: maven:3.9.11-amazoncorretto-21-alpine
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cyberneuron
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=95743286f85f320fc55e341e8c14cb326120523522aa9aa0da05d1d578eeb1e5
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cyberneuron
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: