name: CI

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'maven'

      - name: Run tests with Maven
        run: mvn -B clean test